"""Create urls table

Revision ID: 4cd7fd2d259b
Revises: 8e45dd766b4f
Create Date: 2024-07-26 00:34:54.130586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd7fd2d259b'
down_revision: Union[str, None] = '8e45dd766b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('view_count', sa.Integer(), nullable=True))
    op.alter_column('urls', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('urls', 'short_url',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index('ix_urls_url', table_name='urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_urls_url', 'urls', ['url'], unique=False)
    op.alter_column('urls', 'short_url',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('urls', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('urls', 'view_count')
    # ### end Alembic commands ###
