"""initial migration

Revision ID: 8e45dd766b4f
Revises: 23771ec52585
Create Date: 2024-07-25 22:38:28.806060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e45dd766b4f'
down_revision: Union[str, None] = '23771ec52585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('url', sa.String(), nullable=True))
    op.add_column('urls', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    op.alter_column('urls', 'short_url',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('urls_short_url_key', 'urls', type_='unique')
    op.create_index(op.f('ix_urls_id'), 'urls', ['id'], unique=False)
    op.create_index(op.f('ix_urls_short_url'), 'urls', ['short_url'], unique=True)
    op.create_index(op.f('ix_urls_url'), 'urls', ['url'], unique=False)
    op.drop_column('urls', 'long_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('long_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_urls_url'), table_name='urls')
    op.drop_index(op.f('ix_urls_short_url'), table_name='urls')
    op.drop_index(op.f('ix_urls_id'), table_name='urls')
    op.create_unique_constraint('urls_short_url_key', 'urls', ['short_url'])
    op.alter_column('urls', 'short_url',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('urls', 'expiration_date')
    op.drop_column('urls', 'url')
    # ### end Alembic commands ###
